---
title: Understanding Confounding and Aliasing
author: Mike Denham
date: '2018-11-09'
slug: understanding-confounding-and-aliasing
categories: []
tags: []
header:
  caption: ''
  image: ''
---

Statistical terminology can be confusing.  The terms confounding and aliasing were introduced by different researchers at different times during the development of experimental design theory.  The two terms were introduced in subtly different contexts.  The term confounding was introduced in the late 1920s by Ronald Fisher in the context of blocking experiments.  It was used to describe the situation of deliberately “confounding” effects due to differences in blocks with typically higher order interactions between experimental factors to keep the size of a block to a manageable number.  Later on, in the 1940s when fractional factorial designs were introduced by Finney, the term “aliasing” was used to describe the situation when two different factorial effects (such as two separate two-way interactions) could not be estimated separately from one another using the observed results from the experiment.  There is little practical difference between these two situations and over time it has become widespread practice for the two terms to be used interchangeably.  We will use the term “aliasing” throughout this discussion.
 
Two effects are aliased if their estimates are correlated with each other^^1^^.  In the extreme case of perfect correlation (±1) it becomes mathematically impossible to discern the impact of one effect from the other using the data from the experiment.  Fractional factorial designs do this on purpose.  They lead to designs in which pairs of effects are either completely aliased (i.e. the estimates are perfectly correlated) or they are not aliased at all (i.e. the estimates have a correlation of zero).  For instance, resolution IV fractional factorials have the property that estimates of main effects are uncorrelated with those of any other main effects or two-factor interactions.  At the same time estimates of two-factor interactions will be perfectly correlated with estimates for some other two-factor interactions and uncorrelated with others.  Prior information about what are likely to be the important effects can sometimes be used to choose designs where potentially important effects are only aliased with effects which are scientifically unlikely to exist.  This reliance on both the observed data and our prior knowledge allows us to obtain the required information using fewer experimental resources.  Fractional factorial designs have the desirable feature that they lead to a clear distinction of when estimated effects are unaffected by the size of other effects and when they are not.
 
It is also possible to create designs in which estimates of effects are correlated but not perfectly so.  These designs allow us to mathematically tease out separate effects because their estimates are not perfectly correlated.  Such effects are sometimes referred to as partially aliased.  This can lead to misunderstandings when reading the literature; some authors use aliasing or confounding when they really mean complete aliasing.  In our view, aliasing can refer to either complete or partial aliasing.  The phrase “not completely aliased” (or equivalently not completely confounded) does not mean “not aliased” (or not confounded).  Definitive Screening Designs are an example of a class of experimental designs which have partial aliasing.  In these designs, main effects estimates are not aliased with each other or with any two-factors interactions or quadratic effects.  At the same time, two-factor interactions and quadratic effect estimates are partially aliased with each other.  This partial aliasing makes interpretation of the uncertainty associated with effect estimates much more difficult.  It also makes choosing an appropriate model more difficult.  Even though pairs of effects may not be perfectly correlated with each other, it can still be mathematically impossible to distinguish between the overall impact of two different sets of effects.
 
<hr>
 
^^1^^This isn’t entirely true.  I guess strictly speaking the two effects are aliased if the associated columns of the design matrix are not orthogonal.  When we have two columns that are linearly dependent, we generally include one effect and not the other. The estimated effect is then biased.  (We do not have an estimator for the other term, so we cannot talk about the correlation between them.)  When we have partial aliasing and we fit both terms we have correlation but no bias due to the partially aliased effect.
 
One could think of this as dividing the design matrix into separate sub-matrices where $X_1$ represents effects included in the model and  $X_2$ represents terms effects not included in the model. Note $X_2$ can include *any* effect not included in the model.  These can be explicitly omitted main effects, higher order terms not explicitly considered or even effects associated with unknown process factors.
 
$$y = X_1{\vec\beta_1} + X_2\vec\beta_2 + \epsilon$$
 
We estimate $\vec\beta_1$ as $\hat \beta_1 = \left(X_1^TX_1\right)^{-1}X_1^Ty$, so that
 
$$E\left[\hat \beta_1\right] = \vec\beta_1 + \left(X_1^TX_1\right)^{-1}X_1^TX_2\vec\beta_2$$
and
$$V\left[\hat \beta_1\right] = \left(X_1^TX_1\right)^{-1}\sigma^2.$$
 
If  $X_1^TX_2 = 0$ then $\hat\beta_1$ is an unbiased estimate regardless of the values of $\vec\beta_2$.
 
If $X_1^TX_2 \ne 0$ then $\hat \beta_1$ is a  biased estimate unless $\vec\beta_2 = \vec0.$
 
For the $j$th coefficient in $\hat \beta_1$ (i.e. $\beta_{1j}$) to be unbiased for the corresponding coefficient in $\vec\beta_1$, for each value of $k$, one or other of  $\left[\left(X_1^TX_1\right)^{-1}X_1^TX_2\right]_{jk}$ and $\beta_{2k}$ must be equal to zero. 